name: Deploy Landing Page

on:
  push:
    branches: ["main", "master", "TEST"]

jobs:
  deploy:
    environment: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && 'PROD-SERVER' || 'TEST-SERVER' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".next,public,package.json,package-lock.json,next.config.*,.env"
          target: "/var/www/allfoods-landing"
          strip_components: 0

      - name: Restart WebApp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/allfoods-landing
            npm install --production
            npm run build
            pm2 restart allfoods-premium || pm2 start npm --name "allfoods-premium" -- run start -- -p 3003
            pm2 save
            echo "✅ Landing deploy muvaffaqiyatli!"
